'use client';
import Link from 'next/link';
import { useEffect, useId, useMemo, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ChevronRight, SlidersHorizontal, X, SearchX, Laptop, Tv, ShieldCheck, RotateCcw } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose } from '@/components/ui/sheet';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { filterProducts,formatSpec,currentPrice,type CatalogData,type Filters,type Category } from '@/lib/catalog';
import { ProductCard } from './product-card';

const defaults:Filters={query:'',brands:[],min:0,max:200000,specs:{},sort:'popular',stock:true};
function FilterPanel({base,category,brands,filters,update,reset}:{base:CatalogData["products"];category?:Category;brands:string[];filters:Filters;update:(p:Partial<Filters>)=>void;reset:()=>void}){const prefix=useId();return <div className="filter-panel"><div className="filter-heading"><strong>Фильтры</strong><button onClick={reset} className="text-button" aria-label="Сбросить фильтры"><RotateCcw size={15}/>Сбросить</button></div><fieldset><legend>Цена, ₽</legend><div className="price-inputs"><label><span>от</span><input aria-label="Минимальная цена" inputMode="numeric" type="number" min={0} max={filters.max} value={filters.min||''} placeholder="0" onChange={e=>update({min:Math.min(filters.max,Math.max(0,Number(e.target.value)))})}/></label><label><span>до</span><input aria-label="Максимальная цена" inputMode="numeric" type="number" min={filters.min} max={200000} value={filters.max} onChange={e=>update({max:Math.max(filters.min,Math.min(200000,Number(e.target.value)))})}/></label></div><Slider aria-label="Диапазон цены" min={0} max={200000} step={1000} value={[filters.min,filters.max]} onValueChange={([min,max])=>update({min,max})}/></fieldset><fieldset><legend>Бренд <span>{brands.length}</span></legend>{brands.map(b=><label className="check-row" key={b} htmlFor={prefix+b}><Checkbox id={prefix+b} checked={filters.brands.includes(b)} onCheckedChange={checked=>update({brands:checked?[...filters.brands,b]:filters.brands.filter(v=>v!==b)})}/><span>{b}</span><small>{base.filter(p=>p.brand===b).length}</small></label>)}</fieldset>{category?.attributes.filter(a=>a.filter).map(attr=><fieldset key={attr.key}><legend>{attr.label}</legend><div className="filter-options">{[...new Set(base.map(p=>String(p.specs[attr.key])))].sort((a,b)=>attr.type==='number'?Number(a)-Number(b):a.localeCompare(b)).map(v=>{const values=filters.specs[attr.key]||[];return <label className="check-row" key={v} htmlFor={prefix+attr.key+v}><Checkbox id={prefix+attr.key+v} checked={values.includes(v)} onCheckedChange={checked=>update({specs:{...filters.specs,[attr.key]:checked?[...values,v]:values.filter(x=>x!==v)}})}/><span>{formatSpec(v,attr)}</span></label>;})}</div></fieldset>)}<fieldset><label className="check-row" htmlFor={prefix+'stock'}><Checkbox id={prefix+'stock'} checked={filters.stock} onCheckedChange={v=>update({stock:!!v})}/><span>Только в наличии</span></label></fieldset><div className="filter-note"><ShieldCheck size={23}/><p>Цена товара — без доставки и условий персональных скидок.</p></div></div>;}
export function Catalog({categories,products,category,initialQuery=''}:CatalogData&{category?:Category;initialQuery?:string}) {
 const [filters,setFilters]=useState<Filters>({...defaults,query:initialQuery});
 useEffect(()=>{setFilters({...defaults,query:initialQuery});},[initialQuery,category?.id]);
 const base=useMemo(()=>products.filter(p=>!category||p.categoryId===category.id),[products,category]);
 const results=useMemo(()=>filterProducts(products,category?.id,filters),[products,category,filters]);
 const brands=[...new Set(base.map(p=>p.brand))].sort();
 const activeCount=filters.brands.length+Object.values(filters.specs).flat().length+(filters.min>0||filters.max<200000?1:0);
 const update=(patch:Partial<Filters>)=>setFilters(f=>({...f,...patch}));
 const reset=()=>setFilters({...defaults,query:filters.query});
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool={name:'filter_catalog',title:'Отфильтровать каталог',description:'Apply search, brand and price filters to the visible product catalog.',inputSchema:{type:'object',properties:{query:{type:'string'},brands:{type:'array',items:{type:'string'}},min:{type:'number',minimum:0},max:{type:'number',maximum:200000},sort:{type:'string',enum:['popular','price-asc','price-desc']}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object')throw new Error('Expected filter object');const x=input as Partial<Filters>;if(Object.keys(x).some(k=>!['query','brands','min','max','sort'].includes(k))||(x.query!==undefined&&typeof x.query!=='string')||(x.brands!==undefined&&(!Array.isArray(x.brands)||x.brands.some(b=>typeof b!=='string'||!brands.includes(b))))||(x.min!==undefined&&(!Number.isFinite(x.min)||x.min<0))||(x.max!==undefined&&(!Number.isFinite(x.max)||x.max>200000))||(x.sort!==undefined&&!['popular','price-asc','price-desc'].includes(x.sort)))throw new Error('Invalid filters');const next={...defaults,...x};if(next.min>next.max)throw new Error('Minimum exceeds maximum');flushSync(()=>setFilters(next));return {count:filterProducts(products,category?.id,next).length,filters:next};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return ()=>lifecycle.abort();
 },[products,category?.id,brands.join(',')]);

 return <main id="main" className="container catalog-main">
  <div className="breadcrumb"><Link href="/">Главная</Link><ChevronRight size={13}/><span>{category?category.name:'Каталог техники'}</span></div>
  <div className="page-heading"><div><span className="eyebrow">МЕНЬШЕ СОМНЕНИЙ. БОЛЬШЕ ФАКТОВ.</span><h1>{filters.query?`Результаты для «${filters.query}»`:category?category.name:'Хорошая техника. Честное сравнение.'}</h1><p>{category?category.description:'Все характеристики, предложения магазинов и история цен — в одном месте.'}</p></div><div className="heading-stamp"><ShieldCheck size={20}/><span>Выбираете вы.<br/><strong>Мы сравниваем.</strong></span></div></div>
  {!category&&<div className="category-row">{categories.map(c=><Link key={c.id} className={'category-tile '+c.id} href={'/category/'+c.slug}><div className="category-symbol">{c.id==='laptops'?<Laptop size={27}/>:<Tv size={27}/>}</div><div><strong>{c.name}</strong><span>{products.filter(p=>p.categoryId===c.id).length} моделей · от {new Intl.NumberFormat('ru-RU').format(Math.min(...products.filter(p=>p.categoryId===c.id).map(p=>currentPrice(p)??Infinity)))} ₽</span></div><ArrowUpRight size={20}/></Link>)}</div>}
  <div className="catalog-layout"><aside className="desktop-filters"><FilterPanel base={base} category={category} brands={brands} filters={filters} update={update} reset={reset}/></aside><section className="catalog-results" aria-label="Результаты поиска"><div className="catalog-toolbar"><div><h2>{category?'Подходящие модели':filters.query?'Найденные товары':'В центре внимания'}</h2><span aria-live="polite">{results.length} моделей</span></div><div className="sort-controls"><Sheet><SheetTrigger className="mobile-filter-button"><SlidersHorizontal size={17}/>Фильтры{activeCount>0&&<b>{activeCount}</b>}</SheetTrigger><SheetContent side="left" className="mobile-filter-sheet"><SheetHeader><SheetTitle>Подобрать технику</SheetTitle><SheetDescription>Фильтры применяются сразу.</SheetDescription></SheetHeader><FilterPanel base={base} category={category} brands={brands} filters={filters} update={update} reset={reset}/><SheetClose className="primary-button">Показать {results.length} моделей</SheetClose></SheetContent></Sheet><Select value={filters.sort} onValueChange={sort=>update({sort})}><SelectTrigger aria-label="Сортировка товаров" className="sort-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="popular">По популярности</SelectItem><SelectItem value="price-asc">Сначала дешевле</SelectItem><SelectItem value="price-desc">Сначала дороже</SelectItem></SelectContent></Select></div></div>
  {(activeCount>0||filters.query)&&<div className="active-filters">{filters.query&&<button onClick={()=>{update({query:''});window.history.replaceState(null,'',window.location.pathname);}}>Поиск: {filters.query}<X size={14}/></button>}{filters.brands.map(b=><button key={b} onClick={()=>update({brands:filters.brands.filter(x=>x!==b)})}>{b}<X size={14}/></button>)}{Object.entries(filters.specs).flatMap(([k,vs])=>vs.map(v=><button key={k+v} onClick={()=>update({specs:{...filters.specs,[k]:vs.filter(x=>x!==v)}})}>{formatSpec(v,category?.attributes.find(a=>a.key===k))}<X size={14}/></button>))}{(filters.min>0||filters.max<200000)&&<button onClick={()=>update({min:0,max:200000})}>{filters.min.toLocaleString('ru-RU')}–{filters.max.toLocaleString('ru-RU')} ₽<X size={14}/></button>}</div>}
  {results.length?<div className="product-grid">{results.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<Empty className="empty-state"><EmptyHeader><SearchX size={44}/><EmptyTitle>Ничего не нашлось</EmptyTitle><EmptyDescription>Попробуйте расширить диапазон цены или убрать часть фильтров.</EmptyDescription></EmptyHeader><button className="primary-button" onClick={()=>setFilters({...defaults})}>Сбросить поиск и фильтры</button></Empty>}
  <p className="catalog-footnote">Демонстрационные данные на 10 сентября 2026. Популярность задана в примере каталога.</p></section></div>
 </main>;
}
