'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ChartNoAxesColumnIncreasing,ChevronRight,ArrowLeft,X } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { Table,TableHeader,TableHead,TableRow,TableBody,TableCell } from '@/components/ui/table';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { useComparison } from './app-shell';
import { money,currentPrice,formatSpec,validateComparison,type CatalogData } from '@/lib/catalog';
export function Comparison({products,categories,initialIds}:{initialIds:string[]}&CatalogData) {
 const {selected,replace,ready,clear}=useComparison(),[ids,setIds]=useState(initialIds),[onlyDifferences,setOnlyDifferences]=useState(false);
 useEffect(()=>{if(initialIds.length){const valid=validateComparison(initialIds,products);if(valid.valid){replace(products.filter(p=>initialIds.includes(p.id)));setIds(initialIds);}}else if(ready)setIds(selected.map(p=>p.id));},[ready,initialIds.join(',')]);
 const check=validateComparison(ids,products),items=ids.map(id=>products.find(p=>p.id===id)).filter((p):p is typeof products[number]=>!!p),category=categories.find(c=>c.id===items[0]?.categoryId);
 function remove(id:string){const next=ids.filter(x=>x!==id);setIds(next);replace(products.filter(p=>next.includes(p.id)));window.history.replaceState(null,'','/compare'+(next.length?'?ids='+next.map(encodeURIComponent).join(','):''));}
 function reset(){setIds([]);clear();window.history.replaceState(null,'','/compare');}
 return <main id="main" className="container comparison-main"><div className="breadcrumb"><Link href="/">Главная</Link><ChevronRight size={13}/><span>Сравнение</span></div><div className="comparison-heading"><div><span className="eyebrow">ДЕТАЛИ РЕШАЮТ</span><h1>Сравнение товаров</h1><p className="description-text" style={{margin:0}}>Характеристики рядом. Различия — на виду.</p></div><Link className="secondary-button" href={category?'/category/'+category.slug:'/'}><ArrowLeft size={16}/>Добавить товары</Link></div>{!check.valid||items.length<2?<Empty className="white-panel comparison-empty"><EmptyHeader><ChartNoAxesColumnIncreasing size={45} style={{margin:'0 auto 15px',color:'#7a8bf2'}}/><EmptyTitle>{!check.valid?'Не удалось сравнить товары':items.length===1?'Добавьте ещё одну модель':'Что будем сравнивать?'}</EmptyTitle><EmptyDescription>{!check.valid?check.reason:'Выберите от двух до четырёх товаров из одной категории с помощью кнопки сравнения.'}</EmptyDescription></EmptyHeader><Link className="primary-button" href={category?'/category/'+category.slug:'/'}>Перейти в каталог</Link>{!!ids.length&&<button className="text-button" onClick={reset}>Очистить сравнение</button>}</Empty>:<><div className="comparison-controls"><label htmlFor="only-differences"><Checkbox id="only-differences" checked={onlyDifferences} onCheckedChange={v=>setOnlyDifferences(!!v)}/>Только различия</label><button className="text-button" onClick={reset}><X size={14}/>Очистить сравнение</button></div><div className="comparison-table-wrap"><Table className="comparison-table" style={{minWidth:180+items.length*230}}><TableHeader><TableRow><TableHead className="compare-table-intro">{category?.name}<br/>{items.length} модели в сравнении<br/>Данные демонстрационные</TableHead>{items.map(p=><TableHead key={p.id}><div className="compare-product"><Link href={'/product/'+p.slug}><img src={p.images[0]} alt={p.name}/>{p.name}</Link><div className="compare-price">{currentPrice(p)!==null?money(currentPrice(p)!):'Нет в наличии'}</div><button onClick={()=>remove(p.id)}>Убрать из сравнения</button></div></TableHead>)}</TableRow></TableHeader><TableBody>{[{key:'brand',label:'Бренд',type:'string' as const},...(category?.attributes||[])].map(a=>{const values=items.map(p=>a.key==='brand'?p.brand:p.specs[a.key]),different=new Set(values.map(v=>JSON.stringify(v))).size>1;if(onlyDifferences&&!different)return null;return <TableRow key={a.key} className={different?'different':''}><TableHead scope="row">{a.label}</TableHead>{values.map((v,i)=><TableCell key={items[i].id}>{formatSpec(v,a)}</TableCell>)}</TableRow>})}</TableBody></Table></div><p className="difference-note"><span/>Подсвечены характеристики, которые отличаются.</p></>}</main>;
}
